#include <iostream>
using namespace std;

bool isOdd(int n)
{
    return n%2 !=0;
}
int main()
{
    int a = 1;
    int b = 2;
    int c = 0;
    int upper = 4000000;
    int total = 2;
    while (c < upper)
    {
        c = a + b;
        if (!isOdd(c))
        {
            total += c;
        }
        a = b;
        b = c;


    }
    cout << total << "\n";
    return 0;
}

/*


Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
